# Generated by Django 3.2.6 on 2021-08-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=50024)),
                ('created_by', models.IntegerField()),
                ('is_complete', models.BooleanField()),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
