version: '3.7'
services:
  mongodb_container:
    image: mongo:4.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: $DB_USER
      MONGO_INITDB_ROOT_PASSWORD: $DB_PASSWORD
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db